# Generated by Django 2.0.7 on 2018-07-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrwebapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payment_status',
            field=models.CharField(choices=[('DONE', 'DONE'), ('PENDING', 'PENDING')], default='PENDING', max_length=16, verbose_name='Payment Status'),
        ),
    ]
