# Generated by Django 2.0.7 on 2018-07-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrwebapp', '0003_auto_20180718_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.CharField(max_length=32, verbose_name='Ending Point'),
        ),
        migrations.AlterField(
            model_name='route',
            name='source',
            field=models.CharField(max_length=32, verbose_name='Starting Point'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('source', 'destination')},
        ),
    ]
