# Generated by Django 2.0.7 on 2018-07-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrwebapp', '0004_auto_20180718_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='fare',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Journey Fare'),
        ),
    ]
